export const otp_title = '//h1[contains(text(), "Issuing Bank")]'
export const otp_desc = 'span[class= "help-block"]'
export const otp_field = 'input[id="PaRes"]'
export const ok_btn = 'button[name="ok"]'
export const cancel_btn = 'button[name="cancel"]'
export const resend_btn = 'button[name="resend"]'
export const failed_payment_message = '//div[contains(text(), "Failed to process payment. Please place your order again.")]'
export const ok_failed_btn = '//button[contains(text(), "OK")]'