export const store_title = 'div[class= "title-bar"]'
export const total_price = 'div[class= "header-amount"]'
export const payment_list_title = 'div[class= "payment-list-title"]'
export const credit_card_payment = '(//a[@class= "list"])[1]'
export const credit_card_title = '//span[contains(text(), "Credit/debit card")]'
export const card_number = 'input[autocomplete="cc-number"]'
export const card_expiry = 'input[id="card-expiry"]'
export const card_cvv = 'input[id="card-cvv"]'
export const pay_btn = '//button[contains(text(), "Pay now")]'