export const box_product = 'div[class= "ss-box-inner"]'
export const title_product = 'div[class= "title"]'
export const buy_btn = 'a[class= "btn buy"]'
export const desc_product = 'div[class= "desc"]'
export const transaction_success_title = '//span[contains(text(), "Thank you for your purchase.")]'
export const transaction_failed_title = '//span[contains(text(), "Sorry, something went wrong.")]'